src/main/java/com/ballexca/loucademia/domain/acesso/Acesso.java
package com.ballexca.loucademia.domain.acesso;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.ballexca.loucademia.domain.aluno.Aluno;

@Entity
@Table(name = "ENTRAS_SAIDAS")
public class Acesso implements Serializable {

  @Id
  @Column(name = "ID", nullable = false)
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;
  
  @ManyToOne
  @JoinColumn(name = "ALUNO_ID", nullable = false)
  private Aluno aluno;

  @Column(name = "ENTRADA", nullable = false)
  private LocalDateTime entrada;
  
  @Column(name = "SAIDA", nullable = true)
  private LocalDateTime saida;

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Aluno getAluno() {
    return aluno;
  }

  public void setAluno(Aluno aluno) {
    this.aluno = aluno;
  }

  public LocalDateTime getEntrada() {
    return entrada;
  }

  public void setEntrada(LocalDateTime entrada) {
    this.entrada = entrada;
  }

  public LocalDateTime getSaida() {
    return saida;
  }

  public void setSaida(LocalDateTime saida) {
    this.saida = saida;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("Acesso [getId()=");
    builder.append(getId());
    builder.append(", getAluno()=");
    builder.append(getAluno());
    builder.append(", getEntrada()=");
    builder.append(getEntrada());
    builder.append(", getSaida()=");
    builder.append(getSaida());
    builder.append("]");
    
    return builder.toString();
  }

  @Override
  public int hashCode() {
    return Objects.hash(id);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Acesso other = (Acesso) obj;
    return Objects.equals(id, other.id);
  }
  
}

src/main/java/com/ballexca/loucademia/domain/aluno/Aluno.java
package com.ballexca.loucademia.domain.aluno;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.Year;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ballexca.loucademia.application.util.StringUtils;

@Entity
@Table(name = "ALUNO")
public class Aluno implements Serializable {

  public enum Sexo {
    Masculino, Feminino;
  }

  public enum Situacao {
    Ativo, Inativo, Pendente;
  }

  @Id
  @Column(name = "ID", nullable = false, length = 8)
  private String matricula;

  @Column(name = "NOME", nullable = false, length = 64)
  private String nome;

  @Enumerated
  @Column(name = "SEXO", nullable = false)
  private Sexo sexo;

  @Column(name = "RG", nullable = false, length = 10)
  private Integer rg;

  @Column(name = "NASCIMENTO", nullable = false)
  private LocalDate dataNascimento;

  @Enumerated
  @Column(name = "SITUACAO", nullable = false)
  private Situacao situacao;

  @Column(name = "EMAIL", nullable = false, length = 64)
  private String email;

  @Embedded
  private Endereco endereco = new Endereco();

  @Embedded
  private Telefone telefone = new Telefone();

  public void gerarMatricula(String maxMatricula) {
    Year ano = Year.now();
    
    if (StringUtils.estaVazia(maxMatricula)) {
      maxMatricula = ano + StringUtils.adicionaZeroAEsquerda(0,4);
    }
    
    int sequencial =  Integer.parseInt(maxMatricula.substring(4));
    sequencial++;
    
    this.matricula = ano + StringUtils.adicionaZeroAEsquerda(sequencial, 4);
  }

  public String getMatricula() {
    return matricula;
  }

  public void setMatricula(String matricula) {
    this.matricula = matricula;
  }

  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public Sexo getSexo() {
    return sexo;
  }

  public void setSexo(Sexo sexo) {
    this.sexo = sexo;
  }

  public Integer getRg() {
    return rg;
  }

  public void setRg(Integer rg) {
    this.rg = rg;
  }

  public LocalDate getDataNascimento() {
    return dataNascimento;
  }

  public void setDataNascimento(LocalDate dataNascimento) {
    this.dataNascimento = dataNascimento;
  }

  public Situacao getSituacao() {
    return situacao;
  }

  public void setSituacao(Situacao situacao) {
    this.situacao = situacao;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Endereco getEndereco() {
    return endereco;
  }

  public void setEndereco(Endereco endereco) {
    this.endereco = endereco;
  }

  public Telefone getTelefone() {
    return telefone;
  }

  public void setTelefone(Telefone telefone) {
    this.telefone = telefone;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("Aluno [getMatricula()=");
    builder.append(getMatricula());
    builder.append(", getNome()=");
    builder.append(getNome());
    builder.append(", getSexo()=");
    builder.append(getSexo());
    builder.append(", getRg()=");
    builder.append(getRg());
    builder.append(", getDataNascimento()=");
    builder.append(getDataNascimento());
    builder.append(", getSituacao()=");
    builder.append(getSituacao());
    builder.append(", getEmail()=");
    builder.append(getEmail());
    builder.append(", getEndereco()=");
    builder.append(getEndereco());
    builder.append(", getTelefone()=");
    builder.append(getTelefone());
    builder.append("]");

    return builder.toString();
  }

  @Override
  public int hashCode() {
    return Objects.hash(matricula);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Aluno other = (Aluno) obj;
    return Objects.equals(matricula, other.matricula);
  }
}

src/main/java/com/ballexca/loucademia/domain/aluno/AlunoRepository.java
package com.ballexca.loucademia.domain.aluno;

import java.time.Year;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

@Stateless
public class AlunoRepository {

  @PersistenceContext
  private EntityManager manager;

  public void store(Aluno aluno) {
    manager.persist(aluno);
  }

  public Aluno update(Aluno aluno) {
    return manager.merge(aluno);
  }

  public Aluno findByMatricula(String matricula) {
    return manager.find(Aluno.class, matricula);
  }

  public String getMaxMatriculaAno() {
    return manager
        .createQuery("SELECT MAX(a.matricula) FROM Aluno a WHERE a.matricula LIKE :ano", String.class)
        .setParameter("ano",Year.now() + "%")
        .getSingleResult();
  }
  
  public void delete(String matricula) {
    Aluno aluno = findByMatricula(matricula);

    if (aluno != null) {
      manager.remove(aluno);
    }
  }
}

src/main/java/com/ballexca/loucademia/domain/aluno/Endereco.java
package com.ballexca.loucademia.domain.aluno;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Embeddable
public class Endereco implements Serializable {

  @Column(name = "RUA", nullable = true, length = 128)
  private String rua;

  @Column(name = "NUMERO", nullable = true, length = 6)
  private Integer numero;

  @Column(name = "COMPLEMENTO", nullable = true, length = 32)
  private String complemento;

  @Column(name = "CEP", nullable = true, length = 20)
  private String cep;

  @Column(name = "CIDADE", nullable = false, length = 64)
  private String cidade;

  @ManyToOne
  @JoinColumn(name = "ESTADO_ID", nullable = false)
  private Estado estado = new Estado();

  public String getRua() {
    return rua;
  }

  public void setRua(String rua) {
    this.rua = rua;
  }

  public Integer getNumero() {
    return numero;
  }

  public void setNumero(Integer numero) {
    this.numero = numero;
  }

  public String getComplemento() {
    return complemento;
  }

  public void setComplemento(String complemento) {
    this.complemento = complemento;
  }

  public String getCep() {
    return this.cep;
  }

  public void setCep(String cep) {
    this.cep = cep;
  }

  public String getCidade() {
    return cidade;
  }

  public void setCidade(String cidade) {
    this.cidade = cidade;
  }

  public Estado getEstado() {
    return estado;
  }

  public void setEstado(Estado estado) {
    this.estado = estado;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("Endereco [getRua()=");
    builder.append(getRua());
    builder.append(", getNumero()=");
    builder.append(getNumero());
    builder.append(", getComplemento()=");
    builder.append(getComplemento());
    builder.append(", getCep()=");
    builder.append(getCep());
    builder.append(", getCidade()=");
    builder.append(getCidade());
    builder.append(", getEstado()=");
    builder.append(getEstado());
    builder.append("]");

    return builder.toString();
  }

  @Override
  public int hashCode() {
    return Objects.hash(cidade, complemento, cep, estado, numero, rua);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Endereco other = (Endereco) obj;
    return Objects.equals(cidade, other.cidade) && Objects.equals(complemento, other.complemento)
        && Objects.equals(estado, other.estado) && Objects.equals(numero, other.numero)
        && Objects.equals(rua, other.rua) && Objects.equals(cep, other.cep);
  }

}

src/main/java/com/ballexca/loucademia/domain/aluno/Estado.java
package com.ballexca.loucademia.domain.aluno;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "ESTADO")
public class Estado implements Serializable {

  @Id
  @Column(name = "SIGLA", nullable = false, length = 2)
  private String sigla;
 
  @Column(name = "NOME", nullable = false, length = 30)
  private String nome;
  
  public String getNome() {
    return nome;
  }
  public void setNome(String nome) {
    this.nome = nome;
  }
  public String getSigla() {
    return sigla;
  }
  public void setSigla(String sigla) {
    this.sigla = sigla;
  }
  
  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("Estado [getNome()=");
    builder.append(getNome());
    builder.append(", getSigla()=");
    builder.append(getSigla());
    builder.append("]");
    
    return builder.toString();
  }
  @Override
  public int hashCode() {
    return Objects.hash(sigla);
  }
  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Estado other = (Estado) obj;
    return Objects.equals(sigla, other.sigla);
  }
  
}

src/main/java/com/ballexca/loucademia/domain/aluno/EstadoRepository.java
package com.ballexca.loucademia.domain.aluno;

import java.util.List;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;

@Stateless
public class EstadoRepository {

  @PersistenceContext
  private EntityManager manager;

  public List<Estado> listEstados() {
    TypedQuery<Estado> queryEstados = manager.createQuery("SELECT e FROM Estado e ORDER BY e.nome", Estado.class);
    return queryEstados.getResultList();
  }
}

src/main/java/com/ballexca/loucademia/domain/aluno/Telefone.java
package com.ballexca.loucademia.domain.aluno;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Embeddable;

@Embeddable
public class Telefone implements Serializable {

  @Column(name = "CELULAR_DDD", nullable = false, length = 2)
  private String dddCelular;
  
  @Column(name = "CELULAR_NUMERO", nullable = false, length = 9)
  private String numeroCelular;
 
  @Column(name = "FIXO_DDD", nullable = true, length = 2)
  private String dddFixo;
  
  @Column(name = "FIXO_NUMERO", nullable = true, length = 9)
  private String numeroFixo;
  
  public String getDddCelular() {
    return dddCelular;
  }
  public void setDddCelular(String dddCelular) {
    this.dddCelular = dddCelular;
  }
  public String getNumeroCelular() {
    return numeroCelular;
  }
  public void setNumeroCelular(String numeroCelular) {
    this.numeroCelular = numeroCelular;
  }
  public String getDddFixo() {
    return dddFixo;
  }
  public void setDddFixo(String dddFixo) {
    this.dddFixo = dddFixo;
  }
  public String getNumeroFixo() {
    return numeroFixo;
  }
  public void setNumeroFixo(String numeroFixo) {
    this.numeroFixo = numeroFixo;
  }
  
  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("Telefone [getDddCelular()=");
    builder.append(getDddCelular());
    builder.append(", getNumeroCelular()=");
    builder.append(getNumeroCelular());
    builder.append(", getDddFixo()=");
    builder.append(getDddFixo());
    builder.append(", getNumeroFixo()=");
    builder.append(getNumeroFixo());
    builder.append("]");
    
    return builder.toString();
  }
  
  @Override
  public int hashCode() {
    return Objects.hash(dddCelular, dddFixo, numeroCelular, numeroFixo);
  }
  
  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Telefone other = (Telefone) obj;
    return Objects.equals(dddCelular, other.dddCelular) && Objects.equals(dddFixo, other.dddFixo)
        && Objects.equals(numeroCelular, other.numeroCelular) && Objects.equals(numeroFixo, other.numeroFixo);
  }
  
}

src/main/java/com/ballexca/loucademia/interfaces/aluno/web/AlunoController.java
package com.ballexca.loucademia.interfaces.aluno.web;

import java.io.Serializable;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import com.ballexca.loucademia.application.service.AlunoService;
import com.ballexca.loucademia.application.util.StringUtils;
import com.ballexca.loucademia.domain.aluno.Aluno;
import com.ballexca.loucademia.interfaces.shared.web.Router;

@Named
@RequestScoped
public class AlunoController implements Serializable {
  
  @EJB
  private AlunoService alunoService;
  
  @Inject
  private FacesContext facesContext;
  
  private Aluno aluno = new Aluno();
  
  private String matricula;
  
  private String titulo = "Novo Aluno";
  
  public void carregar() {
    if(!StringUtils.estaVazia(matricula)) {
      aluno = alunoService.findByMatricula(matricula);
      titulo = "Alterar Aluno";
    }
  }
  
  public Object gravar() {
    alunoService.createOrUpdate(aluno);
    facesContext.addMessage(null, new FacesMessage("Dados gravados com sucesso!"));
    
    return Router.mesmaPagina;
  }
 
  public Aluno getAluno() {
    return aluno;
  }

  public void setAluno(Aluno aluno) {
    this.aluno = aluno;
  }
  
  public void setMatricula(String matricula) {
    this.matricula = matricula;
  }
  
  public String getMatricula() {
    return matricula;
  }
  
  public String getTitulo() {
    return titulo;
  }
  
  public boolean isRenderizaPainelMensagem() {
    return !facesContext.getMessageList().isEmpty();
  }
}

src/main/java/com/ballexca/loucademia/interfaces/shared/web/DataController.java
package com.ballexca.loucademia.interfaces.shared.web;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import com.ballexca.loucademia.application.service.DataService;
import com.ballexca.loucademia.domain.aluno.Aluno.Sexo;
import com.ballexca.loucademia.domain.aluno.Aluno.Situacao;
import com.ballexca.loucademia.domain.aluno.Estado;

@Named
@ApplicationScoped
public class DataController implements Serializable {
  
  @EJB
  private DataService dataService;
  
  public List<Sexo> getSexos() {
    return dataService.getSexos();
  }
  
  public List<Situacao> getSituacoes() {
    return dataService.getSituacoes();
  }

  public List<Estado> getEstados() {
    return dataService.listEstados();
  }

}

src/main/webapp/dados_aluno.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
 <ui:composition
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
  xmlns:f="http://xmlns.jcp.org/jsf/core"
  xmlns:h="http://xmlns.jcp.org/jsf/html"
  xmlns:b="http://butterfaces.org/components"
  xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
  xmlns:jsf="http://xmlns.jcp.org/jsf"
  template="layout.xhtml">	
	<f:metadata>
	 <f:viewParam name="matricula" value="#{alunoController.matricula}" />
	 <f:viewAction action="#{alunoController.carregar}" />
	</f:metadata>
	<ui:define name="conteudo">
		<h1>#{alunoController.titulo}</h1>
		
		<h:panelGroup layout="block" rendered="#{alunoController.renderizaPainelMensagem}">
			<div id="infoMessage">
				<h:messages />
			</div>
		</h:panelGroup>
		
		<br />
		
		<form jsf:id="cadastroAlunoForm" autocomplete="off" novalidate="novalidate">
			<input type="hidden" jsf:value="#{alunoController.aluno.matricula}" />
			<fieldset>
				<legend>Dados Pessoais</legend>
				
				<label for="nome">Nome</label><br />
				<input type="text" id="nome" jsf:value="#{alunoController.aluno.nome}" maxlength="64" jsf:label="Nome">
				   <f:validateRequired />
				  <f:validateLength minimum="2" maximum="64" />
				</input><br />
				
				<label for="sexo">Sexo</label><br />
				<select id="sexo" jsf:value="#{alunoController.aluno.sexo}" size="0" jsf:label="Sexo">
					<f:selectItem itemLabel="Escolha..." noSelectionOption="true" />
					<f:selectItems value="#{dataController.sexos}" />
					<f:validateRequired />
				</select><br />
				
				<label for="rg">RG</label><br />
				<input type="text" id="rg" jsf:value="#{alunoController.aluno.rg}" maxlength="10" jsf:label="RG">
				  <f:validateRequired />
				  <f:validateLongRange minimum="10000000" maximum="9999999999" />
				</input><br />
				
				<label for="dataDeNascimento">Data de Nascimento</label><br />
				<input type="date" id="dataDeNascimento" jsf:value="#{alunoController.aluno.dataNascimento}" jsf:label="Data de Nascimento">
				  <f:convertDateTime type="localDate" pattern="yyyy-MM-dd" />
				  <f:validateRequired />
				</input>
			</fieldset>
			
			<br />
			
			<fieldset>
				<legend>Situação</legend>
				<label for="situacao">Situação</label><br />
				<select name="situacao" id="situacao" size="0" jsf:value="#{alunoController.aluno.situacao}" jsf:label="Situação">
					<f:selectItem itemLabel="Escolha..." noSelectionOption="true" />
					<f:selectItems  value="#{dataController.situacoes}" />
					<f:validateRequired />
				</select><br />
			</fieldset>
			
			<br />
			
			<fieldset>
				<legend>Endereço</legend>
				
				<label for="rua">Rua</label><br />
				<input type="text" id="rua" jsf:value="#{alunoController.aluno.endereco.rua}" maxlength="128" jsf:label="Rua">
				  <f:validateLength maximum="128" />
				</input><br />
				
				<label for="">Número</label><br />
				<input type="text" id="numero" jsf:value="#{alunoController.aluno.endereco.numero}" maxlength="6" jsf:label="Número">
				  <f:validateLongRange maximum="999999" />
				</input><br />
				
				<label for="complemento">Complemento</label><br />
				<input type="text" id="complemento" jsf:value="#{alunoController.aluno.endereco.complemento}" maxlength="32" jsf:label="Complemento">
				  <f:validateLength maximum="32" />
				</input><br />
				
				<label for="cidade">Cidade</label><br />
				<input type="text" id="cidade" jsf:value="#{alunoController.aluno.endereco.cidade}" maxlength="64" jsf:label="Cidade">
				  <f:validateRequired />
				  <f:validateLength minimum="2" maximum="64" />
				</input><br />
				
				<label for="estado">Estado</label><br />
				<select id="estado" jsf:value="#{alunoController.aluno.endereco.estado.sigla}" size="0" jsf:label="Estado">
					<f:selectItem itemLabel="Escolha..." noSelectionOption="true" />
					<f:selectItems value="#{dataController.estados}" var="estado" itemLabel="#{estado.nome}" itemValue="#{estado.sigla}" />
					<f:validateRequired />
				</select><br />
				
				<label for="cep">CEP</label><br />
				<input type="text" id="cep" jsf:value="#{alunoController.aluno.endereco.cep}" maxlength="8" jsf:label="CEP">
				  <f:validateLength maximum="8" />
				</input>
			</fieldset>
			
			<br />
			
			<fieldset>
				<legend>Contato</legend>
				<label for="email">E-mail</label><br />
				<input type="email" id="email" jsf:value="#{alunoController.aluno.email}" maxlength="64" jsf:label="E-mail">
				  <f:validateRequired />
				  <f:validateLength maximum="64" />
				  <f:validateRegex pattern=".+@.+" />
				</input><br />
				
				<label for="telefoneCelularDDD">Telefone Celular</label><br />
				<input type="tel" id="telefoneCelularDDD" jsf:value="#{alunoController.aluno.telefone.dddCelular}" maxlength="2" jsf:label="DDD Celular">
				  <f:validateRequired />
				  <f:validateLength minimum="2" maximum="2" />
				</input>&#160;
				<input type="tel" id="telefoneCelularNumero" jsf:value="#{alunoController.aluno.telefone.numeroCelular}" maxlength="9" jsf:label="Telefone Celular">
          <f:validateRequired />
				  <f:validateLength minimum="8" maximum="9" />
				</input><br />
				
				<label for="telefoneFixoDDD">Telefone Fixo</label><br />
				<input type="tel" id="telefoneFixoDDD" jsf:value="#{alunoController.aluno.telefone.dddFixo}" maxlength="2" jsf:label="DDD Fixo">
          <f:validateLength maximum="2" />
				</input>&#160;
				<input type="tel" id="telefoneFixoNumero" jsf:value="#{alunoController.aluno.telefone.numeroFixo}" maxlength="9" jsf:label="Telefone Fixo">
				  <f:validateLength maximum="9" />
				</input>
			</fieldset>
			
			<br />
			
			<input type="submit" value="Gravar" jsf:action="#{alunoController.gravar}" />
			<input type="button" value="Relatório de Acessos" />		
		</form>
	</ui:define>
</ui:composition>

src/main/webapp/layout.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>
<html lang="pt-br"
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
  xmlns:f="http://xmlns.jcp.org/jsf/core"
  xmlns:h="http://xmlns.jcp.org/jsf/html"
  xmlns:b="http://butterfaces.org/components"
  xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
  xmlns:jsf="http://xmlns.jcp.org/jsf">
<head jsf:id="head">
  <meta charset="utf-8" />
  <title>Loucademia</title>

  <link rel="stylesheet" href="css/Loucademia_Estilo.css" />
</head>
<body jsf:id="body">
	<header>
		<img src="images/Loucademia_Logotipo.png" />
		<nav>
			<a jsf:outcome="dados_aluno">Novo aluno</a><br />
			<a jsf:outcome="pesquisa_aluno">Pesquisa de aluno</a><br />
			<a jsf:outcome="controle_acesso">Controle de acesso</a><br />
			<a jsf:outcome="relatorios_entrada_saida">Relatórios de entra e saída</a><br />
			<a jsf:outcome="relatorio_situacoes">Relatório de Situações</a><br />
		</nav>
	</header>
	
	<ui:insert name="conteudo" />
</body>
</html>